-- Datos de prueba para musician_profiles
INSERT INTO musician_profiles
(id, stage_name, genre, country, description, photo_url, photo_public_id, banner_url, banner_public_id, whatsapp, payment_link, payment_alias, cbu, spotify_url, youtube_url, instagram_url, tiktok_url)
VALUES
    (16, 'DJ Echo', 'Electronic', 'USA', 'DJ Echo creates immersive electronic music with a modern twist.', 'https://res.cloudinary.com/dggmk0peo/image/upload/v1757149048/DJ_Echo_e_pypbkb.jpg', 'DJ_Echo_e_pypbkb', 'https://res.cloudinary.com/dggmk0peo/image/upload/v1757149047/DJ_Echo_banner_mwlpoj.jpg', 'DJ_Echo_banner_mwlpoj', '+1-202-555-0171', 'https://paypal.me/djecho', 'DJECHO', '12345678901', 'https://open.spotify.com/artist/djecho', 'https://youtube.com/djecho', 'https://instagram.com/djecho', 'https://tiktok.com/@djecho'),
    (17, 'Luna Sky', 'Pop', 'UK', 'Luna Sky is a rising pop sensation blending soulful lyrics with catchy melodies.', 'https://res.cloudinary.com/dggmk0peo/image/upload/v1757149059/Luna_Sky_hemtkq.jpg', 'Luna_Sky_hemtkq', 'https://res.cloudinary.com/dggmk0peo/image/upload/v1757149058/Luna_Sky_banner_twyeak.jpg', 'Luna_Sky_banner_twyeak', '+44-20-7946-0958', 'https://paypal.me/lunasky', 'LUNASKY', '23456789012', 'https://open.spotify.com/artist/lunasky', 'https://youtube.com/lunasky', 'https://instagram.com/lunasky', 'https://tiktok.com/@lunasky'),
    (18, 'Max Thunder', 'Rock', 'Canada', 'Max Thunder rocks stages with powerful guitar riffs and dynamic vocals.', 'https://res.cloudinary.com/dggmk0peo/image/upload/v1757149062/Max_Thunder_qg0dji.jpg', 'https://res.cloudinary.com/dggmk0peo/image/upload/v1757149062/Max_Thunder_qg0dji.jpg', 'https://res.cloudinary.com/dggmk0peo/image/upload/v1757149061/Max_Thunder_banner_dbtqii.jpg', 'Max_Thunder_banner_dbtqii', '+1-416-555-0199', 'https://paypal.me/maxthunder', 'MAXTHUNDER', '34567890123', 'https://open.spotify.com/artist/maxthunder', 'https://youtube.com/maxthunder', 'https://instagram.com/maxthunder', 'https://tiktok.com/@maxthunder'),
    (19, 'Sofia Rivera', 'Latin', 'Mexico', 'Sofia Rivera brings vibrant Latin rhythms and passionate performances.', 'https://res.cloudinary.com/dggmk0peo/image/upload/v1757149088/Sofia_Rivera_hrq7ly.jpg', 'Sofia_Rivera_hrq7ly', 'https://res.cloudinary.com/dggmk0peo/image/upload/v1757149086/Sofia_Rivera_banner_qxx9cf.jpg', 'Sofia_Rivera_banner_qxx9cf', '+52-55-1234-5678', 'https://paypal.me/sofiarivera', 'SOFIARIVERA', '45678901234', 'https://open.spotify.com/artist/sofiarivera', 'https://youtube.com/sofiarivera', 'https://instagram.com/sofiarivera', 'https://tiktok.com/@sofiarivera'),
    (20, 'Echo Wave', 'EDM', 'Germany', 'Echo Wave produces high-energy EDM tracks that get crowds moving.', 'https://res.cloudinary.com/dggmk0peo/image/upload/v1757149050/Echo_Wave_jpf1yl.jpg', 'Echo_Wave_jpf1yl', 'https://res.cloudinary.com/dggmk0peo/image/upload/v1757149049/Echo_Wave_banner_pwsmly.jpg', 'Echo_Wave_banner_pwsmly', '+49-30-555-0145', 'https://paypal.me/echowave', 'ECHOWAVE', '56789012345', 'https://open.spotify.com/artist/echowave', 'https://youtube.com/echowave', 'https://instagram.com/echowave', 'https://tiktok.com/@echowave'),
    (21, 'Nova Star', 'Hip Hop', 'USA', 'Nova Star is an innovative hip hop artist known for clever lyrics and beats.', 'https://res.cloudinary.com/dggmk0peo/image/upload/v1757149069/Nova_Star_hzbktl.jpg', 'Nova_Star_hzbktl', 'https://res.cloudinary.com/dggmk0peo/image/upload/v1757149068/Nova_Star_banner_d3v6bi.jpg', 'Nova_Star_banner_d3v6bi', '+1-310-555-0182', 'https://paypal.me/novastar', 'NOVASTAR', '67890123456', 'https://open.spotify.com/artist/novastar', 'https://youtube.com/novastar', 'https://instagram.com/novastar', 'https://tiktok.com/@novastar'),
    (22, 'Kai Moon', 'R&B', 'Australia', 'Kai Moon blends soulful R&B vocals with smooth instrumentals.', 'https://res.cloudinary.com/dggmk0peo/image/upload/v1757149053/Kai_Moon_tpg0op.jpg', 'Kai_Moon_tpg0op', 'https://res.cloudinary.com/dggmk0peo/image/upload/v1757149052/Kai_Moon_banner_ok3wp9.jpg', 'Kai_Moon_banner_ok3wp9', '+61-2-5550-1234', 'https://paypal.me/kaimoon', 'KAIMOON', '78901234567', 'https://open.spotify.com/artist/kaimoon', 'https://youtube.com/kaimoon', 'https://instagram.com/kaimoon', 'https://tiktok.com/@kaimoon'),
    (23, 'Lila Frost', 'Indie', 'France', 'Lila Frost creates unique indie tracks with emotional depth.', 'https://res.cloudinary.com/dggmk0peo/image/upload/v1757149056/Lila_Frost_mmssij.jpg', 'Lila_Frost_mmssij', 'https://res.cloudinary.com/dggmk0peo/image/upload/v1757149055/Lila_Frost_banner_d6chea.jpg', 'Lila_Frost_banner_d6chea', '+33-1-5550-5678', 'https://paypal.me/lilafrost', 'LILAFROST', '89012345678', 'https://open.spotify.com/artist/lilafrost', 'https://youtube.com/lilafrost', 'https://instagram.com/lilafrost', 'https://tiktok.com/@lilafrost'),
    (24, 'Orion Blaze', 'Metal', 'Norway', 'Orion Blaze delivers intense metal performances with epic riffs.', 'https://res.cloudinary.com/dggmk0peo/image/upload/v1757149073/Orion_Blaze_cjknjb.jpg', 'Orion_Blaze_cjknjb', 'https://res.cloudinary.com/dggmk0peo/image/upload/v1757149071/Orion_Blaze_banner_lq584o.jpg', 'Orion_Blaze_banner_lq584o', '+47-22-555-0101', 'https://paypal.me/orionblaze', 'ORIONBLAZE', '90123456789', 'https://open.spotify.com/artist/orionblaze', 'https://youtube.com/orionblaze', 'https://instagram.com/orionblaze', 'https://tiktok.com/@orionblaze'),
    (25, 'Maya Sky', 'Pop', 'Sweden', 'Maya Sky is a pop artist known for catchy hooks and vibrant performances.', 'https://res.cloudinary.com/dggmk0peo/image/upload/v1757149065/Maya_Sky_tkpyae.jpg', 'Maya_Sky_tkpyae', 'https://res.cloudinary.com/dggmk0peo/image/upload/v1757149064/Maya_Sky_banner_jfvgys.jpg', 'https://res.cloudinary.com/dggmk0peo/image/upload/v1757149064/Maya_Sky_banner_jfvgys.jpg', '+46-8-5550-4321', 'https://paypal.me/mayasky', 'MAYASKY', '01234567890', 'https://open.spotify.com/artist/mayasky', 'https://youtube.com/mayasky', 'https://instagram.com/mayasky', 'https://tiktok.com/@mayasky'),
    (26, 'Ryder Storm', 'Rap', 'UK', 'Ryder Storm creates sharp rap lyrics with hard-hitting beats.', 'https://res.cloudinary.com/dggmk0peo/image/upload/v1757149078/Ryder_Storm_ly0lac.jpg', 'Ryder_Storm_ly0lac', 'https://res.cloudinary.com/dggmk0peo/image/upload/v1757149074/Ryder_Storm_banner_nmwey2.jpg', 'Ryder_Storm_banner_nmwey2', '+44-20-5550-8765', 'https://paypal.me/ryderstorm', 'RYDERSTORM', '11234567890', 'https://open.spotify.com/artist/ryderstorm', 'https://youtube.com/ryderstorm', 'https://instagram.com/ryderstorm', 'https://tiktok.com/@ryderstorm'),
    (27, 'Selena Nova', 'Electronic', 'Italy', 'Selena Nova produces mesmerizing electronic tracks for festivals.', 'https://res.cloudinary.com/dggmk0peo/image/upload/v1757149083/Selena_Nova_l8fipf.jpg', 'Selena_Nova_l8fipf', 'https://res.cloudinary.com/dggmk0peo/image/upload/v1757149080/Selena_Nova_banner_f8az3o.jpg', 'Selena_Nova_banner_f8az3o', '+39-06-5550-9012', 'https://paypal.me/selenanova', 'SELENANOVA', '22345678901', 'https://open.spotify.com/artist/selenanova', 'https://youtube.com/selenanova', 'https://instagram.com/selenanova', 'https://tiktok.com/@selenanova'),
    (28, 'Tobias King', 'Jazz', 'Netherlands', 'Tobias King is a talented jazz musician with smooth melodies.', 'https://res.cloudinary.com/dggmk0peo/image/upload/v1757149094/Tobias_King_l66q4d.jpg', 'Tobias_King_l66q4d', 'https://res.cloudinary.com/dggmk0peo/image/upload/v1757149089/Tobias_King_banner_vbnmj2.jpg', 'Tobias_King_banner_vbnmj2', '+31-20-5550-3456', 'https://paypal.me/tobiasking', 'TOBIASKING', '33456789012', 'https://open.spotify.com/artist/tobiasking', 'https://youtube.com/tobiasking', 'https://instagram.com/tobiasking', 'https://tiktok.com/@tobiasking'),
    (29, 'Vera Moon', 'Soul', 'Brazil', 'Vera Moon captivates audiences with her soulful voice.', 'https://res.cloudinary.com/dggmk0peo/image/upload/v1757149099/Vera_Moon_dsymqn.jpg', 'Vera_Moon_dsymqn', 'https://res.cloudinary.com/dggmk0peo/image/upload/v1757149095/Vera_Moon_banner_np6qqv.jpg', 'Vera_Moon_banner_np6qqv', '+55-21-5550-7890', 'https://paypal.me/veramoon', 'VERAMOON', '44567890123', 'https://open.spotify.com/artist/veramoon', 'https://youtube.com/veramoon', 'https://instagram.com/veramoon', 'https://tiktok.com/@veramoon'),
    (30, 'Zane Frost', 'Rock', 'USA', 'Zane Frost rocks the stage with energy and powerful guitar solos.', 'https://res.cloudinary.com/dggmk0peo/image/upload/v1757149103/Zane_Frost_bk4unv.jpg', 'Zane_Frost_bk4unv', 'https://res.cloudinary.com/dggmk0peo/image/upload/v1757149102/Zane_Frost_banner_naljp5.jpg', 'Zane_Frost_banner_naljp5', '+1-212-555-0199', 'https://paypal.me/zanefrost', 'ZANEFROST', '55678901234', 'https://open.spotify.com/artist/zanefrost', 'https://youtube.com/zanefrost', 'https://instagram.com/zanefrost', 'https://tiktok.com/@zanefrost');
