INSERT INTO users (name, email, password, role) VALUES
-- FAN users
('Alice Johnson', 'alice.johnson@example.com', '$2a$10$bNTIJoN929SFN5/yYzpsjuGCZt2MYSRQrdWGjpGao2Px5VH0QE2rS', 'FAN'),
('Benjamin Carter', 'benjamin.carter@example.com', '$2a$10$bNTIJoN929SFN5/yYzpsjuGCZt2MYSRQrdWGjpGao2Px5VH0QE2rS', 'FAN'),
('Clara Montgomery', 'clara.montgomery@example.com', '$2a$10$bNTIJoN929SFN5/yYzpsjuGCZt2MYSRQrdWGjpGao2Px5VH0QE2rS', 'FAN'),
('David Langford', 'david.langford@example.com', '$2a$10$bNTIJoN929SFN5/yYzpsjuGCZt2MYSRQrdWGjpGao2Px5VH0QE2rS', 'FAN'),
('Eva Thompson', 'eva.thompson@example.com', '$2a$10$bNTIJoN929SFN5/yYzpsjuGCZt2MYSRQrdWGjpGao2Px5VH0QE2rS', 'FAN'),
('Felix Grant', 'felix.grant@example.com', '$2a$10$bNTIJoN929SFN5/yYzpsjuGCZt2MYSRQrdWGjpGao2Px5VH0QE2rS', 'FAN'),
('Grace Whitman', 'grace.whitman@example.com', '$2a$10$bNTIJoN929SFN5/yYzpsjuGCZt2MYSRQrdWGjpGao2Px5VH0QE2rS', 'FAN'),
('Henry Lawson', 'henry.lawson@example.com', '$2a$10$bNTIJoN929SFN5/yYzpsjuGCZt2MYSRQrdWGjpGao2Px5VH0QE2rS', 'FAN'),
('Isabel Fletcher', 'isabel.fletcher@example.com', '$2a$10$bNTIJoN929SFN5/yYzpsjuGCZt2MYSRQrdWGjpGao2Px5VH0QE2rS', 'FAN'),
('Jack Sullivan', 'jack.sullivan@example.com', '$2a$10$bNTIJoN929SFN5/yYzpsjuGCZt2MYSRQrdWGjpGao2Px5VH0QE2rS', 'FAN'),
('Karen Bishop', 'karen.bishop@example.com', '$2a$10$bNTIJoN929SFN5/yYzpsjuGCZt2MYSRQrdWGjpGao2Px5VH0QE2rS', 'FAN'),
('Liam Kennedy', 'liam.kennedy@example.com', '$2a$10$bNTIJoN929SFN5/yYzpsjuGCZt2MYSRQrdWGjpGao2Px5VH0QE2rS', 'FAN'),
('Mia Gallagher', 'mia.gallagher@example.com', '$2a$10$bNTIJoN929SFN5/yYzpsjuGCZt2MYSRQrdWGjpGao2Px5VH0QE2rS', 'FAN'),
('Noah Porter', 'noah.porter@example.com', '$2a$10$bNTIJoN929SFN5/yYzpsjuGCZt2MYSRQrdWGjpGao2Px5VH0QE2rS', 'FAN'),
('Olivia Harper', 'olivia.harper@example.com', '$2a$10$bNTIJoN929SFN5/yYzpsjuGCZt2MYSRQrdWGjpGao2Px5VH0QE2rS', 'FAN'),

-- MUSICIAN users
('Peter Donovan', 'peter.donovan@example.com', '$2a$10$bNTIJoN929SFN5/yYzpsjuGCZt2MYSRQrdWGjpGao2Px5VH0QE2rS', 'MUSICIAN'),
('Quinn Matthews', 'quinn.matthews@example.com', '$2a$10$bNTIJoN929SFN5/yYzpsjuGCZt2MYSRQrdWGjpGao2Px5VH0QE2rS', 'MUSICIAN'),
('Rachel O Connor', 'rachel.oconnor@example.com', '$2a$10$bNTIJoN929SFN5/yYzpsjuGCZt2MYSRQrdWGjpGao2Px5VH0QE2rS', 'MUSICIAN'),
('Samuel Pierce', 'samuel.pierce@example.com', '$2a$10$bNTIJoN929SFN5/yYzpsjuGCZt2MYSRQrdWGjpGao2Px5VH0QE2rS', 'MUSICIAN'),
('Tara Benson', 'tara.benson@example.com', '$2a$10$bNTIJoN929SFN5/yYzpsjuGCZt2MYSRQrdWGjpGao2Px5VH0QE2rS', 'MUSICIAN'),
('Ulysses Grant', 'ulysses.grant@example.com', '$2a$10$bNTIJoN929SFN5/yYzpsjuGCZt2MYSRQrdWGjpGao2Px5VH0QE2rS', 'MUSICIAN'),
('Victoria Lane', 'victoria.lane@example.com', '$2a$10$bNTIJoN929SFN5/yYzpsjuGCZt2MYSRQrdWGjpGao2Px5VH0QE2rS', 'MUSICIAN'),
('William Frost', 'william.frost@example.com', '$2a$10$bNTIJoN929SFN5/yYzpsjuGCZt2MYSRQrdWGjpGao2Px5VH0QE2rS', 'MUSICIAN'),
('Xavier Holt', 'xavier.holt@example.com', '$2a$10$bNTIJoN929SFN5/yYzpsjuGCZt2MYSRQrdWGjpGao2Px5VH0QE2rS', 'MUSICIAN'),
('Yvonne Blake', 'yvonne.blake@example.com', '$2a$10$bNTIJoN929SFN5/yYzpsjuGCZt2MYSRQrdWGjpGao2Px5VH0QE2rS', 'MUSICIAN'),
('Zachary Cole', 'zachary.cole@example.com', '$2a$10$bNTIJoN929SFN5/yYzpsjuGCZt2MYSRQrdWGjpGao2Px5VH0QE2rS', 'MUSICIAN'),
('Amelia Ross', 'amelia.ross@example.com', '$2a$10$bNTIJoN929SFN5/yYzpsjuGCZt2MYSRQrdWGjpGao2Px5VH0QE2rS', 'MUSICIAN'),
('Brandon Knight', 'brandon.knight@example.com', '$2a$10$bNTIJoN929SFN5/yYzpsjuGCZt2MYSRQrdWGjpGao2Px5VH0QE2rS', 'MUSICIAN'),
('Catherine Hale', 'catherine.hale@example.com', '$2a$10$bNTIJoN929SFN5/yYzpsjuGCZt2MYSRQrdWGjpGao2Px5VH0QE2rS', 'MUSICIAN'),
('Daniel Ford', 'daniel.ford@example.com', '$2a$10$bNTIJoN929SFN5/yYzpsjuGCZt2MYSRQrdWGjpGao2Px5VH0QE2rS', 'MUSICIAN');
