-- Datos de prueba para fan_profiles
INSERT INTO fan_profiles_ecos (id, photo_url, photo_public_id, country) VALUES
    (1, '', '', 'USA'),
    (2, '', '', 'Canada'),
    (3, '', '', 'UK'),
    (4, '', '', 'Australia'),
    (5, '', '', 'Germany'),
    (6, '', '', 'France'),
    (7, '', '', 'Spain'),
    (8, '', '', 'Italy'),
    (9, '', '', 'Netherlands'),
    (10, '', '', 'Brazil'),
    (11, '', '', 'Mexico'),
    (12, '', '', 'Sweden'),
    (13, '', '', 'Norway'),
    (14, '', '', 'Japan'),
(15, '', '', 'South Korea');

-- Datos de prueba para fan_interest_genres
INSERT INTO fan_interest_genres_ecos (fan_profile_id, genre) VALUES
    (1, 'Rock'),
    (1, 'Pop'),
    (2, 'Jazz'),
    (2, 'Blues'),
    (3, 'Classical'),
    (3, 'Opera'),
    (4, 'Electronic'),
    (4, 'House'),
    (5, 'Hip Hop'),
    (5, 'Rap'),
    (6, 'Reggae'),
    (6, 'Ska'),
    (7, 'Country'),
    (7, 'Folk'),
    (8, 'Metal'),
    (8, 'Punk'),
    (9, 'Soul'),
    (9, 'R&B'),
    (10, 'Salsa'),
    (10, 'Merengue'),
    (11, 'Pop'),
    (11, 'Dance'),
    (12, 'Rock'),
    (12, 'Indie'),
    (13, 'Jazz'),
    (13, 'Soul'),
    (14, 'K-Pop'),
    (14, 'R&B'),
    (15, 'Electronic'),
    (15, 'Trance');